name: deploy-search-band-artist-backbone

on:
  push:
    branches:
    - main

env:
  TICKET_MASTER_API_KEY: ${{ secrets.TICKET_MASTER_API_KEY }}
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
# This job installs dependencies, builds the SBAB, and pushes it to `gh-pages`
jobs:
  deploy-SBAB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: yarn

      # Build the SBAB
      - name: Build the SBAB
        run: yarn webpack
        env:
          ENVIRONMENT: production        

      # Push the SBAB's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./